spring:
  profile: dev
  datasource:
    driverClassName: org.h2.Driver
    password: 1235
    url: jdbc:h2:mem:dcbapp-dev
    username: sdr
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect