#my.custom.proprties : "alllllliiiii"


#spring:
#  profiles:
#    active:
#      - main
##      - jdbc
##      - 3th

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ddd #(the name of database)
    username: postgres # (the username that default is "postgres")
    password: postgres # (the password that i set is "postgres")
    jpa:
      hibernate:
        ddl-auto:   update #create-drop #
      # by defulat this is false
      show-sql: true    # when run or hibernate execute command or query  it will be displayed in your ide or in the logs of your application
      properties:
        hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect


# todo: if you want to have many data base setting in diffrent profile do not have then in application.yml place them in profile file, no setting in here

# todo: if you want to create sata base in yml use this : createDatabaseIfNotExist=true (it will create without goring to another app)
# url: jdbc:mysql://localhost:3306/createdDataBase?createDatabaseIfNotExist=true


##########
## (the name ot database,not server the item that you see in database folder in pgadmin4)
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/university # (database or schema name ,not server name)
#    username: root # (the user name of ,mysql server ,not database or schema)
#    password:      # (the password of ,mysql server ,not database or schema)
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
## This will create table automatically in your database
#### postgresql

#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/test
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## use upper one i think better spring console sail this in red color
##spring.datasource.driver-class-name=com.mysql.jdbc.Driver
