my.custom.proprties : "from profile dev"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/university # (database or schema name ,not server name)
    username: root # (the user name of ,mysql server ,not database or schema)
    password:      # (the password of ,mysql server ,not database or schema)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# This will create table automatically in your database
### postgresql
