my.custom.proprties : "alllllliiiii"


spring:
  profiles:
    active:
      - dev
#      - test
#      - 3th



### The following 3 profiles are active: "dev", "fff", "ggg" even we do not create them



##########
# (the name ot database,not server the item that you see in database folder in pgadmin4)
#spring:
  datasource:
    url: jdbc:mysql://localhost:3306/university # (database or schema name ,not server name)
    username: root # (the user name of ,mysql server ,not database or schema)
    password:      # (the password of ,mysql server ,not database or schema)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# This will create table automatically in your database
### postgresql

#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/test
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## use upper one i think better spring console sail this in red color
##spring.datasource.driver-class-name=com.mysql.jdbc.Driver
