mv.custome.properties=hello from the application.properties
env=hello from application.properties

# DataSource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/sprintDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.platform=postgres

# JPA/Hibernate configuration (optional)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

